services:
  myscrapers-sbi-test:
    image: myscrapers-sbi:latest
    container_name: myscrapers-sbi-test
    environment:
      - wsAddr=katarina.int.azuki.blue:7317 # your browser value
      - TZ="JST-9"
    env_file:
      - sbi-token.env
    volumes:
      - ./browser/:/data/
