services:
  myscrapers-sbi-test:
    image: myscrapers-sbi:latest
    container_name: myscrapers-sbi
    environment:
      - chromeAddr=http://example.com/4444/wd/hub # your value
      - TZ="JST-9"
    env_file:
      - sbi-token.env
    volumes:
      - ./browser/:/data/
