services:
  myscrapers-mf-test:
    image: myscrapers-mf:latest
    container_name: myscrapers-mf
    environment:
      - TZ="JST-9"
    env_file:
      - moneyforward-token.env
    volumes:
      - ./browser/:/data/
