services:
  # myscrapers-sbi-test:
  #   image: myscrapers-sbi:latest
  #   container_name: myscrapers-sbi
  #   environment:
  #     - chromeAddr=http://example.com:4444/wd/hub # your value
  #     - TZ="JST-9"
  #   env_file:
  #     - sbi-token.env
  #   volumes:
  #     - ./browser/:/data/
  myscrapers-sbi-test:
    image: myscrapers-mf:latest
    container_name: myscrapers-sbi
    environment:
      - chromeAddr=http://example.com:4444/wd/hub # your value
      - TZ="JST-9"
      - urls="https://moneyforward.com/bs/portfolio,https://moneyforward.com/cf"
    env_file:
      - moneyforward-token.env
    volumes:
      - ./browser/:/data/
