services:
  myscrapers-mf:
    build:
      context: ..
      dockerfile: build/moneyforward/Dockerfile
    image: myscrapers-mf:latest
    container_name: myscrapers-mf
    environment:
      TZ: Asia/Tokyo
      MF_OUTPUT_DIR: /data/out
    volumes:
      - .:/data
    command: ["moneyforward", "--fetch"]
