name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21.0

    - name: go build
      run: make bin-linux-amd64

    - name: run e2e (test github)
      run: build/bin/myscrapers download test-github
      env:
        wsAddr: "localhost:7317"
    services:
      go-rod:
        image: ghcr.io/go-rod/rod:v0.116.2
        ports:
        - 7317:7317
