name: Pytest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: install requirements.txt
      run: pip install -r src/moneyforward/requirements.txt
    - name: Run pytest
      run: pytest -v
